@echo ""
@echo "MacBRTool V1.0.0 by David R (Muerto)"
@echo "Make sure the device is plugged in!"
@echo ""
@echo "To update the BootROM, type 'updatebr.nsh' and press return."
@echo "The machine will power down automatically after completion."
@echo ""
@echo "Type 'reset -s', then press enter to shut down."
@echo ""
